# @format

name: nipat
description: A new Flutter project.

module:
  androidX: true

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.2+1
  firebase_storage: ^3.1.1
  algolia: ^0.1.7
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.3+1
  logger: ^0.8.3
  dio: ^3.0.8
  scoped_model: ^1.0.1
  qrcode_reader: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
